# Generated by Django 5.0.4 on 2024-04-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0003_gaming_email_gaming_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=50)),
                ('numDevice', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='gaming',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gaming',
            name='email',
            field=models.CharField(default='johndoe@gmail.com', max_length=50),
        ),
    ]
