# Generated by Django 5.0.4 on 2024-04-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0004_devices_gaming_position_alter_gaming_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaming',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
