# Generated by Django 5.0.4 on 2024-04-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0006_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(default='johndoe@gmail.com', max_length=50),
        ),
    ]
