# Generated by Django 5.0.4 on 2024-04-23 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0007_rename_name_users_username_alter_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaming',
            name='email',
        ),
        migrations.RemoveField(
            model_name='gaming',
            name='redID',
        ),
    ]
