# Generated by Django 5.0.4 on 2024-04-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('redID', models.IntegerField(max_length=10)),
                ('device', models.CharField(max_length=20)),
                ('time', models.DateField()),
            ],
        ),
    ]
