# Generated by Django 5.0.4 on 2024-04-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaming',
            name='redID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gaming',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
