# Generated by Django 5.0.4 on 2024-04-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0002_alter_gaming_redid_alter_gaming_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaming',
            name='email',
            field=models.CharField(default='yousuck@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='gaming',
            name='status',
            field=models.CharField(default='inActive', max_length=20),
        ),
    ]
